### ISSUE TITLE
[FeatureRequest] Add current QueryExecution status or Download status

### ISSUE THREAD

**Issue by hegerdes** [westnordost/osmapi-overpass#1]
Hey, just found you lib and really like it 👍

## Request
I might use it for an university project if my prof allows it (It is his software)

Just want to ask for an additional feature. If you run a big query with a large response the program is just running the download but does not give any status information. 

`OverpassStatus` just gives you the status of overpass. Not of the current running query. It would be great if you could add a feature that gives back the current query status or the current size of the download buffer. This basically confirms that osmapi is still working. 

## Implementation:
Just an idea: You can create a Status class (that runs in a separate thread) and just gives gack the size of the currently downloaded information. Since you are using typical http this should't be that complicated.

Keep on going ✌

**Comment by westnordost** [comment]
Actually, it is already possible to do just that. Just let your `MapDataHandler` update your UI (asynchronously)

```
overpassDao.queryElements(
    "[bbox:13.8,35.5,14.9,36.3]; nwr[shop]; out meta;",
    new MapDataHandler {
        @Override void handle(Node node) {
            postProgressAsynchronouslyForUI();
            doWhateverYouDoWithANode();
        }
        // and the same for ways, relations, bounding boxes
    }
);
```
