### ISSUE TITLE
Any chance to upgrade this as a module and support Java 11+?

### ISSUE THREAD

**Issue by javasuns** [westnordost/osmapi-overpass#4]
Any chance to upgrade this as a module and support Java 11+?
Thank you for your work :)

**Comment by westnordost** [comment]
Hey javasuns, well, it works of course on Java 11, but I've not heard about Java module support so far, so from my side this is a no. 

You are however welcome to create a PR for that, I assume it would just be about adding some lines to the gradle build configuration or something? 🤷‍♀️
